### PR TITLE
Added french language

### PR DESCRIPTION
**Pull request by foxdog05000**
Hi, I really liked your app because I was looking for an app like this one. So I took the liberty of adding French to your application.
I was not able to test if it works properly because the readme did not contain any information on how to test and build the application.

### CODE REVIEW

**Comment by z17** [comment]
Hello!
Thank you for contribution!

To run app you should do 
`npm install`
`npm run dev`
I will add some information about build and run app from the source files in README file.

Also you forgot to add new language in setting window. And I wrote some comments to your commit.

**Comment by z17** [comment]
I added information about run and build: https://github.com/z17/home-accounting-system#contributing

**Comment by foxdog05000** [comment]
Thank you for your welcome as well as for having added explanations in order to be able to contribute and especially to be able to run the application in dev mode.

So I reviewed my French translations a little bit. I have also taken your comments into account. I replaced the "else if" with a "switch" that I think will allow the addition of an additional language much easier. And I added the "french" language to the "select" in the parameters.

**Review by z17 — APPROVED** [review]

**Comment by z17** [comment]
Thank you, looks good. And it's fine, that Cromberg will have French translation in next release. I changed target branch to dev.
Your commits will fall in master with next release. 

If you want to use app with French right now, just build it from dev branch.

**Comment by foxdog05000** [comment]
Great :)

**Pull request merged**
